global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'telegram-bot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['telegram-bot:8080']
    scrape_interval: 10s

  - job_name: 'audio-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['audio-service:8080']
    scrape_interval: 10s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s